# Generated by Django 3.2 on 2021-04-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud_blog.comment'),
            preserve_default=False,
        ),
    ]
