# Generated by Django 3.2 on 2021-04-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_blog', '0004_auto_20210422_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='timestamp',
        ),
    ]
