# Generated by Django 3.2 on 2021-04-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_blog', '0005_remove_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
